In [ ]:
a = 1

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('data.xlsx')

C:\Users\pooko\anaconda3\envs\bibiml\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\pooko\anaconda3\envs\bibiml\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [5]:
df

,거래ID,거래일자,직원ID,직원명,부서,지역,판매채널,고객유형,제품군,제품명,단가,판매량,할인율,매출액,원가,이익,결제수단,고객만족도,반품여부
0,T0001,2026-02-16,E001,김민준,영업1팀,서울,오프라인매장,소상공인,노트북,비즈니스 노트북,1250000,5,0.05,5937500,4500000,1437500,현금,5,N
1,T0002,2026-05-08,E007,조성민,기업영업팀,대전,온라인몰,개인,노트북,울트라북,1580000,4,0.00,6320000,4676800,1643200,계좌이체,3,N
2,T0003,2026-01-10,E009,장도윤,영업지원팀,광주,기업계약,중소기업,소프트웨어,오피스 라이선스,220000,9,0.15,1683000,752400,930600,후불결제,4,N
3,T0004,2026-02-16,E002,이서연,영업1팀,서울,전화주문,대기업,주변기기,무선 마우스,59000,2,0.15,100300,64900,35400,신용카드,3,N
4,T0005,2026-04-12,E009,장도윤,영업지원팀,광주,전화주문,공공기관,모니터,32인치 모니터,490000,5,0.05,2327500,1641500,686000,계좌이체,5,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,T0096,2026-05-16,E001,김민준,영업1팀,서울,기업계약,공공기관,주변기기,무선 키보드,89000,2,0.05,169100,103240,65860,계좌이체,2,N
96,T0097,2026-05-05,E012,오세훈,영업2팀,대구,기업계약,공공기관,태블릿,10인치 태블릿,680000,1,0.10,612000,469200,142800,계좌이체,2,N
97,T0098,2026-05-20,E007,조성민,기업영업팀,대전,전화주문,공공기관,모니터,32인치 모니터,490000,2,0.08,901600,656600,245000,법인카드,4,N
98,T0099,2026-05-15,E007,조성민,기업영업팀,대전,전화주문,개인,모니터,27인치 모니터,340000,8,0.12,2393600,1795200,598400,신용카드,4,N
99,T0100,2026-03-22,E007,조성민,기업영업팀,대전,오프라인매장,중소기업,태블릿,10인치 태블릿,680000,1,0.10,612000,469200,142800,법인카드,5,N

In [ ]:
read_excel('data.xlsx')

In [31]:
print('안녕하세요')

안녕하세요

In [23]:
a = 88

In [25]:
print(a)

88

In [19]:
df

,거래ID,거래일자,직원ID,직원명,부서,지역,판매채널,고객유형,제품군,제품명,단가,판매량,할인율,매출액,원가,이익,결제수단,고객만족도,반품여부
0,T0001,2026-02-16,E001,김민준,영업1팀,서울,오프라인매장,소상공인,노트북,비즈니스 노트북,1250000,5,0.05,5937500,4500000,1437500,현금,5,N
1,T0002,2026-05-08,E007,조성민,기업영업팀,대전,온라인몰,개인,노트북,울트라북,1580000,4,0.00,6320000,4676800,1643200,계좌이체,3,N
2,T0003,2026-01-10,E009,장도윤,영업지원팀,광주,기업계약,중소기업,소프트웨어,오피스 라이선스,220000,9,0.15,1683000,752400,930600,후불결제,4,N
3,T0004,2026-02-16,E002,이서연,영업1팀,서울,전화주문,대기업,주변기기,무선 마우스,59000,2,0.15,100300,64900,35400,신용카드,3,N
4,T0005,2026-04-12,E009,장도윤,영업지원팀,광주,전화주문,공공기관,모니터,32인치 모니터,490000,5,0.05,2327500,1641500,686000,계좌이체,5,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,T0096,2026-05-16,E001,김민준,영업1팀,서울,기업계약,공공기관,주변기기,무선 키보드,89000,2,0.05,169100,103240,65860,계좌이체,2,N
96,T0097,2026-05-05,E012,오세훈,영업2팀,대구,기업계약,공공기관,태블릿,10인치 태블릿,680000,1,0.10,612000,469200,142800,계좌이체,2,N
97,T0098,2026-05-20,E007,조성민,기업영업팀,대전,전화주문,공공기관,모니터,32인치 모니터,490000,2,0.08,901600,656600,245000,법인카드,4,N
98,T0099,2026-05-15,E007,조성민,기업영업팀,대전,전화주문,개인,모니터,27인치 모니터,340000,8,0.12,2393600,1795200,598400,신용카드,4,N
99,T0100,2026-03-22,E007,조성민,기업영업팀,대전,오프라인매장,중소기업,태블릿,10인치 태블릿,680000,1,0.10,612000,469200,142800,법인카드,5,N

In [21]:
# 데이터 타입
# 숫자(정수, 소수점), 문자, 날짜....
type(df)

pandas.core.frame.DataFrame

In [7]:
a = 1

In [ ]:
# 숫자(int:정수, 소수점:float), 문자str, 날짜....
# 판다스로 불러온 엑셀: DataFrame

In [25]:
df

,거래ID,거래일자,직원ID,직원명,부서,지역,판매채널,고객유형,제품군,제품명,단가,판매량,할인율,매출액,원가,이익,결제수단,고객만족도,반품여부
0,T0001,2026-02-16,E001,김민준,영업1팀,서울,오프라인매장,소상공인,노트북,비즈니스 노트북,1250000,5,0.05,5937500,4500000,1437500,현금,5,N
1,T0002,2026-05-08,E007,조성민,기업영업팀,대전,온라인몰,개인,노트북,울트라북,1580000,4,0.00,6320000,4676800,1643200,계좌이체,3,N
2,T0003,2026-01-10,E009,장도윤,영업지원팀,광주,기업계약,중소기업,소프트웨어,오피스 라이선스,220000,9,0.15,1683000,752400,930600,후불결제,4,N
3,T0004,2026-02-16,E002,이서연,영업1팀,서울,전화주문,대기업,주변기기,무선 마우스,59000,2,0.15,100300,64900,35400,신용카드,3,N
4,T0005,2026-04-12,E009,장도윤,영업지원팀,광주,전화주문,공공기관,모니터,32인치 모니터,490000,5,0.05,2327500,1641500,686000,계좌이체,5,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,T0096,2026-05-16,E001,김민준,영업1팀,서울,기업계약,공공기관,주변기기,무선 키보드,89000,2,0.05,169100,103240,65860,계좌이체,2,N
96,T0097,2026-05-05,E012,오세훈,영업2팀,대구,기업계약,공공기관,태블릿,10인치 태블릿,680000,1,0.10,612000,469200,142800,계좌이체,2,N
97,T0098,2026-05-20,E007,조성민,기업영업팀,대전,전화주문,공공기관,모니터,32인치 모니터,490000,2,0.08,901600,656600,245000,법인카드,4,N
98,T0099,2026-05-15,E007,조성민,기업영업팀,대전,전화주문,개인,모니터,27인치 모니터,340000,8,0.12,2393600,1795200,598400,신용카드,4,N
99,T0100,2026-03-22,E007,조성민,기업영업팀,대전,오프라인매장,중소기업,태블릿,10인치 태블릿,680000,1,0.10,612000,469200,142800,법인카드,5,N

In [115]:
df.sample(2)

,거래ID,거래일자,직원ID,직원명,부서,지역,판매채널,고객유형,제품군,제품명,단가,판매량,할인율,매출액,원가,이익,결제수단,고객만족도,반품여부
0,T0001,2026-02-16,E001,김민준,영업1팀,서울,오프라인매장,소상공인,노트북,비즈니스 노트북,1250000,5,0.05,5937500,4500000,1437500,현금,5,N
46,T0047,2026-04-27,E002,이서연,영업1팀,서울,온라인몰,공공기관,주변기기,무선 마우스,59000,6,0.10,318600,194700,123900,현금,4,N

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   거래ID    100 non-null    object
 1   거래일자    100 non-null    datetime64[ns]
 2   직원ID    100 non-null    object
 3   직원명     100 non-null    object
 4   부서      100 non-null    object
 5   지역      100 non-null    object
 6   판매채널    100 non-null    object
 7   고객유형    100 non-null    object
 8   제품군     100 non-null    object
 9   제품명     100 non-null    object
 10  단가      100 non-null    int64
 11  판매량     100 non-null    int64
 12  할인율     100 non-null    float64
 13  매출액     100 non-null    int64
 14  원가      100 non-null    int64
 15  이익      100 non-null    int64
 16  결제수단    100 non-null    object
 17  고객만족도   100 non-null    int64
 18  반품여부    100 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(6), object(11)
memory usage: 15.0+ KB

In [119]:
df.describe()

,거래일자,단가,판매량,할인율,매출액,원가,이익,고객만족도
count,100,1.000000e+02,100.000000,100.000000,1.000000e+02,1.000000e+02,1.000000e+02,100.000000
mean,2026-03-19 05:45:36,4.738800e+05,6.830000,0.072100,2.257901e+06,1.515972e+06,7.419290e+05,3.690000
min,2026-01-02 00:00:00,5.900000e+04,1.000000,0.000000,8.455000e+04,5.162000e+04,3.293000e+04,2.000000
25%,2026-02-12 18:00:00,8.900000e+04,3.000000,0.030000,6.477000e+05,4.420625e+05,1.869000e+05,3.000000
50%,2026-03-22 12:00:00,3.500000e+05,5.500000,0.080000,1.606500e+06,8.360000e+05,5.236000e+05,4.000000
75%,2026-05-03 06:00:00,6.800000e+05,10.000000,0.120000,3.510000e+06,2.268000e+06,1.131900e+06,4.000000
max,2026-05-28 00:00:00,1.580000e+06,15.000000,0.150000,7.900000e+06,5.846000e+06,2.970000e+06,5.000000
std,NaN,4.536323e+05,4.424576,0.052729,1.985998e+06,1.483129e+06,6.892253e+05,0.939536