In [197]:
from pathlib import Path
import os

os.startfile(Path.cwd())

In [2]:
import pandas as pd
import numpy as np

In [179]:
df1 = pd.read_excel('sample_data.xlsx', sheet_name=0)
df2 = pd.read_excel('sample_data.xlsx', sheet_name=1)

In [69]:
lst = df1.columns.to_list()
lst

['transaction_id',
 'transaction_date',
 'employee_id',
 'customer_type',
 'product_name',
 'category',
 'unit_price',
 'quantity',
 'discount_rate',
 'unit_cost',
 '이름',
 '팀']

In [97]:
lst[0:5]

['transaction_id',
 'transaction_date',
 'employee_id',
 'customer_type',
 'product_name']

In [105]:
['transaction_date', 'employee_id', 'customer_type']
df1.loc[5:15, ['transaction_date', 'employee_id', '이름'] ]

   transaction_date employee_id   이름
5        2026-06-23        E004  최유진
6        2026-02-17        E004  최유진
7        2026-05-01        E001  김민준
8        2026-05-13        E006  강수빈
9        2026-04-23        E001  김민준
10       2026-03-07        E008  윤하은
11       2026-06-17        E007  조성민
12       2026-03-13        E009  장도윤
13       2026-02-18        E010  임지아
14       2026-02-28        E008  윤하은
15       2026-05-31        E008  윤하은

In [119]:
df1[['employee_id', '이름']]

    employee_id   이름
0          E001  김민준
1          E004  최유진
2          E010  임지아
3          E007  조성민
4          E009  장도윤
..          ...  ...
995        E005  정현우
996        E004  최유진
997        E009  장도윤
998        E005  정현우
999        E012  오세훈

[1000 rows x 2 columns]

In [129]:
a = 1250000
a > 1000000

True

In [175]:
con1 = df1['unit_price'] > 1300000
con2 = df1['quantity'] <= 2
df1[ con1 & con2 | con3 ]

(15, 12)

In [81]:
df1.head(5)

,transaction_id,transaction_date,employee_id,customer_type,product_name,category,unit_price,quantity,discount_rate,unit_cost,이름,팀
0,T00001,2026-03-08,E001,중소기업,비즈니스 노트북,노트북,1250000,7,0.01,900000,김민준,영업1팀
1,T00002,2026-03-19,E004,소상공인,10인치 태블릿,태블릿,680000,10,0.01,469000,최유진,영업2팀
2,T00003,2026-03-17,E010,중소기업,데이터 분석 패키지,소프트웨어,540000,3,0.03,238000,임지아,영업지원팀
3,T00004,2026-03-03,E007,중소기업,울트라북,노트북,1580000,1,0.00,1169000,조성민,기업영업팀
4,T00005,2026-05-26,E009,중소기업,무선 키보드,주변기기,89000,15,0.06,52000,장도윤,영업지원팀

In [199]:
df = df1.merge(df2, how='left', on='employee_id')

In [210]:
df.columns

Index(['transaction_id', 'transaction_date', 'employee_id', 'customer_type',
       'product_name', 'category', 'unit_price', 'quantity', 'discount_rate',
       'unit_cost', 'employee_name', 'department', 'region', 'position',
       'hire_date', 'employment_status', 'specialty_category'],
      dtype='object')

In [268]:
df.groupby('department').agg(
    판매량 = ('quantity','sum'),
    평균단가 = ('unit_price','mean'),
    소속직원수_고객수 = ('employee_id','nunique'),
    총매출 = ('총매출액','sum')
)

             판매량           평균단가  소속직원수_고객수         총매출
department
기업영업팀       1740  766668.571429          2  1186382000
영업1팀        2118  903720.338983          3  1745690000
영업2팀        2263  631329.059829          3  1268580000
영업지원팀       2176  432123.595506          2   643745000
온라인영업팀      2109  418604.519774          2   637947000

In [224]:
cond3 = df['department'] == '영업1팀'
df[cond3]['employee_id'].unique()

array(['E001', 'E011', 'E002'], dtype=object)

In [226]:
a = 3
b = 2
a * b

6

In [228]:
df.columns

Index(['transaction_id', 'transaction_date', 'employee_id', 'customer_type',
       'product_name', 'category', 'unit_price', 'quantity', 'discount_rate',
       'unit_cost', 'employee_name', 'department', 'region', 'position',
       'hire_date', 'employment_status', 'specialty_category'],
      dtype='object')

In [232]:
df

,transaction_id,transaction_date,employee_id,customer_type,product_name,category,unit_price,quantity,discount_rate,unit_cost,employee_name,department,region,position,hire_date,employment_status,specialty_category
0,T00001,2026-03-08,E001,중소기업,비즈니스 노트북,노트북,1250000,7,0.01,900000,김민준,영업1팀,서울,대리,2023-02-13,재직,노트북
1,T00002,2026-03-19,E004,소상공인,10인치 태블릿,태블릿,680000,10,0.01,469000,최유진,영업2팀,경기,대리,2022-09-19,재직,태블릿
2,T00003,2026-03-17,E010,중소기업,데이터 분석 패키지,소프트웨어,540000,3,0.03,238000,임지아,영업지원팀,인천,사원,2024-07-01,재직,모니터
3,T00004,2026-03-03,E007,중소기업,울트라북,노트북,1580000,1,0.00,1169000,조성민,기업영업팀,대전,차장,2019-11-11,재직,소프트웨어
4,T00005,2026-05-26,E009,중소기업,무선 키보드,주변기기,89000,15,0.06,52000,장도윤,영업지원팀,광주,대리,2022-12-12,재직,주변기기
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,T00996,2026-02-18,E005,개인,오피스 라이선스,소프트웨어,220000,10,0.06,84000,정현우,온라인영업팀,서울,과장,2020-03-16,재직,소프트웨어
996,T00997,2026-02-16,E004,소상공인,12인치 태블릿 Pro,태블릿,920000,10,0.04,653000,최유진,영업2팀,경기,대리,2022-09-19,재직,태블릿
997,T00998,2026-03-23,E009,중소기업,데이터 분석 패키지,소프트웨어,540000,3,0.00,238000,장도윤,영업지원팀,광주,대리,2022-12-12,재직,주변기기
998,T00999,2026-03-13,E005,공공기관,울트라북,노트북,1580000,9,0.13,1169000,정현우,온라인영업팀,서울,과장,2020-03-16,재직,소프트웨어
999,T01000,2026-05-27,E012,소상공인,12인치 태블릿 Pro,태블릿,920000,2,0.03,653000,오세훈,영업2팀,대구,과장,2020-08-24,휴직,모니터

In [230]:
a = df['unit_price'] * df['quantity']

0       8750000
1       6800000
2       1620000
3       1580000
4       1335000
         ...
995     2200000
996     9200000
997     1620000
998    14220000
999     1840000
Length: 1000, dtype: int64

In [254]:
df3 = pd.read_excel('sample_data.xlsx', sheet_name=0)
df3

,transaction_id,transaction_date,employee_id,customer_type,product_name,category,unit_price,quantity,discount_rate,unit_cost
0,T00001,2026-03-08,E001,중소기업,비즈니스 노트북,노트북,1250000,7,0.01,900000
1,T00002,2026-03-19,E004,소상공인,10인치 태블릿,태블릿,680000,10,0.01,469000
2,T00003,2026-03-17,E010,중소기업,데이터 분석 패키지,소프트웨어,540000,3,0.03,238000
3,T00004,2026-03-03,E007,중소기업,울트라북,노트북,1580000,1,0.00,1169000
4,T00005,2026-05-26,E009,중소기업,무선 키보드,주변기기,89000,15,0.06,52000
...,...,...,...,...,...,...,...,...,...,...
995,T00996,2026-02-18,E005,개인,오피스 라이선스,소프트웨어,220000,10,0.06,84000
996,T00997,2026-02-16,E004,소상공인,12인치 태블릿 Pro,태블릿,920000,10,0.04,653000
997,T00998,2026-03-23,E009,중소기업,데이터 분석 패키지,소프트웨어,540000,3,0.00,238000
998,T00999,2026-03-13,E005,공공기관,울트라북,노트북,1580000,9,0.13,1169000
999,T01000,2026-05-27,E012,소상공인,12인치 태블릿 Pro,태블릿,920000,2,0.03,653000

In [264]:
df['총매출액'] = df['unit_price'] * df['quantity']

In [195]:
df.to_excel('result.xlsx')